language : java
jdk:
  - openjdk-1.8

branches:
  only:
    - master

#Travis CI Home
#그레이들을 통해 의존성을 받으면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때 다시 받지 않도록
cache :
  directories:
    - '$HOME/ .m2/repository'
    - '$HOME/ .gradle'

#Gradlew에 접근하지 못하는 문제 해결
before_install:
  - chmod +x gradlew

#master 브랜치에 푸시되었을 때 수행하는 명령어
script: "./gradlew clean build"

#CI => Email 알림
notifications:
  email :
    recipients:
      - gjgudrn1114@naver.com