version: 0.0
#프로젝트 버전이 아님
os: linux
files:
  - source:  /
  #Codedeploy에서 전달해 준 파일 중 destination으로 이동할 파일 지정 => 전체 파일
  #무중단 배포는 step3를 사용하기로 변경
    destination: /home/ec2-user/app/step3/zip
    overwrite: yes

#Codedeploy에서 EC2 서버로 넘겨 준 파일들을 모두 ec2-user 권한으 갖도록 한다.
permissions:
  - object:  /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

#Codedeploy 배포 단계에서 실행할 명령어 지정, ApplicationStart 단계에서 deploy.sh를 ec2-user 권한으로 실행
hooks:
  AfterInstall:
    - location: stop.sh #엔진엑스와 연결되어 있찌 않은 스프링부트 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh #엔진엑스와 연결되어 있지 않는 Port로 새 버전의 스프링부트 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh #start.sh로 실행한 새 스프링부트가 정상적으로 실행됬는지 체크
      timeout: 60
      runas: ec2-user